name: pocket-js-server

services: 
  pg:
    image: bitnami/postgresql:14.13.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=inorbit